config/routes.rb
Tm2::Application.routes.draw do

  # resources :callists
  # resources :calls


  resources :departments

  resources :companies

  resources :actions

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "setdate" => "aorders#setdate", :as => "setdate"
  post "fillautos" => "onlineautos#fillautos", :as => "fillautos"
  match "setonduty" => "onlineautos#setonduty", :as => "setonduty", via: [:get, :post]
  match "setosort" => "aorders#setosort", :as => "setosort", via: [:get, :post]
  match "aorders/:id/cancel" =>"aorders#ocancel", :as => "aorder_cancel", via: [:get, :post]
  match "uporderstable" => "aorders#uporderstable", :as =>"uporderstable", via: [:get, :post]
  match "tabel" => "actions#tabel", :as =>"tabel", via: [:get, :post]
  # post "password_reset" => "users#password_reset", :as => "password_reset"
  match "aorders/:id/edit_odometer" =>"aorders#edit_odometer", :as => "edit_aorder_odometer", via: [:get, :post]

  match "stat" => "stat#index", :as =>"stat", via: [:get, :post]
  match "stat_xml" => "stat#index_xml", :as =>"stat_xml", via: [:get, :post]
  match "routelist" => "stat#routelist", :as =>"routelist", via: [:get, :post]


#  get "onlineautos/:action/:id" => "onlineautos#index", :as=>"onlineautos"

  resources :users
  resources :sessions
  resources :onlineautos

  resources :aautos
  resources :aorders

  match '/set_day_status' => 'aorders#set_day_status', :as=>'set_day_status', via: [:get, :post]


  root :to => "sessions#new"
 
end

app/models/aorder.rb
# encoding: utf-8

class Aorder < ActiveRecord::Base
  belongs_to :aauto;
  belongs_to :odate;
  belongs_to :user;
  belongs_to :department;
  validates :onname, :presence=>true;
#  validates :ondepartment, :presence=>true; - вместо него просто department
  validates :department, :presence=>true;
  validates :contact, :presence=>true;
  validates :adestination, :presence=>true;
  validates :ftime, :presence=>true;
  validates :totime, :presence=>true;

  validates :odobegin, :presence=>true;
  validates :odoend, :presence=>true;
  validates :outofcity, :presence=>true;
  validates :user, :presence=>true;

  before_update :check_rights;
  before_update :check_is_date_closed;
  before_validation :replace_nil_with_zero;


  after_save :make_odate_be_used

  attr_accessor :is_updating_odometer
  attr_accessor :ttmid;

# upd. спустя 2 года: странная логика с :ttmid но лень переделывать:
# перед Aorder.save / update в контроллере в ttmid прописывается id пользователя, который
# пытается сохранить/обновить данные, потом вызывается  before_update который дергает check_rights 
# и вот уже тут анализируется этот id
# кстаи логика нормальная а имя свойства конченное. Но таки лень переделывать.
# спустя еще 2 года: Таки логика - говно, но переделывать все еще лень.


  def replace_nil_with_zero
    self.odobegin = 0 if !self.odobegin
    self.odoend = 0 if !self.odoend
    self.outofcity = 0 if !self.outofcity
  end


  def make_odate_be_used
    self.odate.was_used=true
    self.odate.save!
  end

  def department_name
    self.department.name
  end

  def check_rights
  #    Убрали возможность редактировать свои заявки, только админ.
  #    if (ttmid.to_i==Aorder.find_by_id(self.id).user_id) or (User.find_by_id(ttmid).userlevel_id==::ADMIN_ID)
    if (User.find_by_id(ttmid).userlevel_id==::ADMIN_ID) or 
        (User.find_by_id(ttmid).userlevel_id==::COMPANY_ADMIN_ID) or
        ( 
          (ttmid.to_i==self.user_id) and 
          (self.aauto_id==nil or self.aauto_id==::NOAUTO_ID or is_updating_odometer)
        ) or 
        (User.find_by_id(ttmid).userlevel_id==::DRIVERUSER_ID)or 
        (User.find_by_id(ttmid).userlevel_id==::DIRECTOR_ID)
      res=true
    else
      self.errors.add(:ttmid, "нет прав на изменеие, только для Администратора!")
      res=false
    end
    res
  end

  def check_is_date_closed
    res=true
    if odate.isclosed
      res=false
      self.errors.add(:odate, "Невозможно выполнить: дата закрыта!")
    else
      res=true
    end
    res
  end

  def duration_seconds
    distance >0 ? (self.totime.seconds_since_midnight - self.ftime.seconds_since_midnight) : 0
  end
  

  def is_d_busy(d_id, t)
    res=false
    if not self.iscanceled
      if (self.ftime.seconds_since_midnight<=t and t<self.totime.seconds_since_midnight) and d_id==self.aauto_id
        res=true
      end
    end
    res
  end

  def distance
    self.odoend-self.odobegin
  end

  def self.get_by_dates(date_begin, date_end, sort_orders_by='aorders.id')
    join_str = "LEFT OUTER JOIN `odates` ON `odates`.`id` = `aorders`.`odate_id`"
    Aorder.joins(join_str).where("thedate >= ? AND thedate <= ? AND iscanceled=false", date_begin, date_end).order(sort_orders_by)
  end

end

app/controllers/aorders_controller.rb
# encoding: utf-8

class AordersController < ApplicationController
  before_action :require_login
  before_action :is_admin, :only => [:set_day_status]
  before_action :is_day_closed, :only => [:ocancel, :new, :create, :update, :destroy]

  def uporderstable
    if session[:user] && !is_not_tm2_user?

      last_today_act = session[:user].actions.where("created_at>'#{DateTime.current.beginning_of_day.to_s(:db)}' and created_at<'#{DateTime.current.end_of_day.to_s(:db)}'").last

      last_today_act.update_attributes!(
        :kind=>"stay_in",
        :updated_at => DateTime.current
      )

      @odate = session[:working_date]
      session[:sort_orders_by]||='id'
      @aorders = Aorder.joins("LEFT OUTER JOIN `aautos` ON `aautos`.`id` = `aorders`.`aauto_id`").where("odate_id=#{@odate.id} AND iscanceled=false").order(session[:sort_orders_by]).order(:ftime)
      @aorder = Aorder.new
      @aorder.odate=@odate
      @aorder.iscanceled=false
      @aorder.outofcity=0
      @aorder.user_id=session[:user].id if session[:user]
      @aorder.ftime=Time.now.localtime
      @aorder.totime=Time.now.localtime

      @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)

      @onlineauto=Onlineauto.new
      @onlineauto.odate_id=@odate.id

    elsif session[:user] && is_not_tm2_user?
      last_today_act = session[:user].actions.where("created_at>'#{DateTime.current.beginning_of_day.to_s(:db)}' and created_at<'#{DateTime.current.end_of_day.to_s(:db)}'").last
      last_today_act.update_attributes!(
        :kind=>"stay_in",
        :updated_at => DateTime.current
      )
      render :nothing => true
    else
      logger.info("No user logged in!")
      redirect_to root_url, :notice => "No user logged in!"
    end

  end

  def set_day_status
    begin
      @odate=Odate.set_day_status(params)
      session[:working_date]=@odate
      session[:error_text]='Готово.'
    rescue TraficError => e
      session[:error_text]="Ошибка: #{e.message}"
    end
    flash[:notice]=session[:error_text]
    redirect_to aorders_path
  end

  def setdate
    session[:working_date]=Odate.get_or_create_by_date(params[:tek_date])
    redirect_to aorders_path
  end

#  def setosort
#    session[:sort_orders_by]=params[:sorton]
#    redirect_to aorders_path
#  end

  def ocancel
    @aorder=Aorder.find_by_id(params[:id])
    @aorder.iscanceled=true
    @aorder.ttmid=session[:user].id
    @aorder.save!
    redirect_to aorders_path
  end

  # GET /aorders
  # GET /aorders.xml
  def index

    @error_text=session[:error_text]
    session[:error_text]=nil
    @odate = session[:working_date]

    params[:sorton] ? (session[:sort_orders_by] = params[:sorton]) : (session[:sort_orders_by]||='id')

    @aorders = Aorder.joins("LEFT OUTER JOIN `aautos` ON `aautos`.`id` = `aorders`.`aauto_id`").where("odate_id=#{@odate.id} AND iscanceled=false").order(session[:sort_orders_by]).order(:ftime)
    @aorder = Aorder.new

    @aorder.odobegin = ''
    @aorder.odoend = ''
    @aorder.outofcity = ''

    @aorder.odate=@odate
    @aorder.iscanceled=false
    @aorder.user_id=session[:user].id
    @aorder.ftime=Time.now.localtime
    @aorder.totime=Time.now.localtime

    @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)

    @onlineauto=Onlineauto.new
    @onlineauto.odate_id=@odate.id

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aorder }
    end

  end

  # GET /aorders/1
  # GET /aorders/1.xml
  def show
    @aorder = Aorder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @aorder }
    end
  end

  # GET /aorders/new
  # GET /aorders/new.xml
  def new
    @aorder = Aorder.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aorder }
    end
  end

  # GET /aorders/1/edit
  def edit

    @odate = session[:working_date]
    @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)
  
    @aorder = Aorder.find(params[:id])
    @aorder.user_id=session[:user].id unless is_admin?
    @aorder.ttmid=session[:user].id

    @aorder.odobegin = '' if @aorder.odobegin == 0
    @aorder.odoend = '' if @aorder.odoend == 0
    @aorder.outofcity = '' if @aorder.outofcity == 0
    
  end

  def edit_odometer

    @odate = session[:working_date]
    @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)
    @aorder = Aorder.find(params[:id])
    @aorder.user_id = session[:user].id unless is_admin?

#вот здесь костыль с правами на редактирование
    @aorder.ttmid = session[:user].id
    @aorder.is_updating_odometer = true

    respond_to do |format|
      format.html
    end
  end

  # POST /aorders
  # POST /aorders.xml
  def create
    @odate = session[:working_date]    
    @aorder = Aorder.new(params[:aorder])
    @aorder.ttmid=session[:user].id
    @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)
        
    respond_to do |format|
      if @aorder.save
        format.html { redirect_to(aorders_path, :notice => 'Aorder was successfully created.') }
        format.xml  { render :xml => @aorder, :status => :created, :location => @aorder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aorder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aorders/1
  # PUT /aorders/1.xml
  def update
    @odate = session[:working_date]
    @aorder = Aorder.find(params[:id])
    @aorder.ttmid=session[:user].id

    @onlineautos=Onlineauto.find_all_by_odate_id_puls_empty(@odate.id)

    respond_to do |format|
      if @aorder.update_attributes(params[:aorder])
        format.html { redirect_to(aorders_path, :notice => 'Заказ изменен.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aorder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aorders/1
  # DELETE /aorders/1.xml
  def destroy
    @aorder = Aorder.find(params[:id])
    @aorder.ttmid=session[:user].id
    @aorder.destroy

    respond_to do |format|
      format.html { redirect_to(aorders_url) }
      format.xml  { head :ok }
    end
  end



end

app/helpers/aorders_helper.rb
module AordersHelper

  def td_odometer(odobegin, odoend, outofcity, args={}, &block )
    classes='hoverable'

    if (odobegin and odoend and outofcity)
    	classes+=' badodometer' if (odoend-odobegin-outofcity)>100 or (odoend-odobegin-outofcity)<0
    else
    	classes+=' badodometer'
    end

    args[:class] = classes
    content_tag(:td, args, &block )

  end

end

app/views/aorders/_body.erb
<% @aorders.each do |aorder| %>
  <tr >
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.id %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.onname %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.department.name if aorder.department %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.contact %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.adestination %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.ftime.strftime("%H:%M") %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.totime.strftime("%H:%M") %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= link_to aorder.aauto.name+' ('+aorder.aauto.autodesc+')', aorder.aauto if aorder.aauto %></td>
    <td class= 'hoverable' data-orderid='[<%=aorder.id%>]' > <%= aorder.comment %></td>
    

    <%= td_odometer( aorder.odobegin, aorder.odoend, aorder.outofcity, :"data-orderid"=>"[#{aorder.id}]") do %>
        <%= aorder.odobegin  %>
    <%end %>

  
    <%= td_odometer( aorder.odobegin, aorder.odoend, aorder.outofcity, :"data-orderid"=>"[#{aorder.id}]") do %>
        <%= aorder.odoend %>
    <%end %>

    <%= td_odometer( aorder.odobegin, aorder.odoend, aorder.outofcity, :"data-orderid"=>"[#{aorder.id}]") do %>
        <%= aorder.distance %>
    <%end %>

    <%= td_odometer( aorder.odobegin, aorder.odoend, aorder.outofcity, :"data-orderid"=>"[#{aorder.id}]") do %>
        <%= aorder.outofcity%>
    <%end %>


    <% if ((is_admin?(aorder.user.company_id) or (is_director? || !aorder.aauto )) and !@odate.isclosed)%>
      <td><%= link_to 'Измен. заказ', edit_aorder_path(aorder) %></td>
    <%elsif is_current_user_or_admin?(aorder.user_id) and !@odate.isclosed%>
      <td><%= link_to 'Измен. пробег', edit_aorder_odometer_path(aorder) %></td>
    <%elsif is_current_user_driver? and !@odate.isclosed%>
      <td><%= link_to 'Измен. пробег', edit_aorder_odometer_path(aorder) %></td>
    <%else%>
      <td><%= link_to 'Детали', aorder_path(aorder) %></td>
    <%end%>

      <%=
        #link_to 'Удал', aorder, :confirm => 'Вы уверены?', :method => :delete настоящее удаление нам не надо
      %>

    <td>
      <%= link_to 'Удал.', aorder_cancel_path(aorder), :confirm => 'Вы уверены?' if (
        is_admin? or is_company_admin?(aorder.user.company_id) or
        ( is_current_user_or_admin?(aorder.user_id) and
        (  (aorder.aauto_id==nil or aorder.aauto_id==::NOAUTO_ID) )) and
        ( !@odate.isclosed )
      )%>

    </td>


    <% if is_admin?  %>
        <td><%= aorder.user.name %></td>
    <%end%>
  </tr>
<% end %>

app/views/aorders/_olist.erb
    Список существующих на данный момент заказов:
    <table class="allorderlist"
      <%= "id=table_inactive" if @odate.isclosed%>
      <%= "id=table_active" if not @odate.isclosed%> >
      
      <%= render 'head' %>
      <%= render 'body' %>

    </table>

app/views/aorders/_onlineautos.erb
<% if @onlineauto.errors.any? %>
  <td colspan="8">
    <div id="error_explanation">
      <h2><%= pluralize(@aonlineautos.errors.count, "ошибки! ") %> - ошибки  делают сохранение невозможным.:</h2>
      <ul>
      <% @aorder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </td>
  <br/>
  <%end%>
Справочник доступных автомобилей:

<%= button_to 'Заполнить из предыдущего дня', fillautos_path if is_admin?||is_company_admin?%>
<table class="onlineautolist">
  <tr>
    <th class="name">Автомобиль</th>
    <th class="Водитель">Водитель</th>
    <th class="autonumber">Госномер авто</th>
    <th class="contact">Тел. водителя</th>
    <th class="worktime">Время за день</th>
    <th class="duty">Дежурный?</th>

    <%
      t=0.hours
      while t <= 23.hours do %>
        <%  if  t.gcd(1.hour.to_i)==1.hour%>
          <% if t/3600<9 or (t/3600>=13 and t/3600<14) or t/3600>=18 %>
            <th colspan="6" class="notworkingtime"><%=t/3600%>-<%=t/3600+1%></th>
          <%else%>
            <th colspan="6" class="workingtime"><%=t/3600%>-<%=t/3600+1%></th>
          <%end%>
        <%end%>

      <%
        t+=10.minutes
        end
      %>
    <th class="todel"> </th>      

  </tr>


<% @onlineautos.each do |onld| %>
  <tr>
    <td><%= onld.aauto.name if onld.aauto %></td>
    <td><%= onld.aauto.autodesc if onld.aauto %></td>
    <td><%= onld.aauto.autonumber if onld.aauto %></td>
    <td><%= onld.aauto.contact if onld.aauto %></td>
    <td><%= onld.work_time %></td>
    <td><%= onld.onduty ? 'Дежурный' : 'Нет' %>
        <%= link_to 'Изменить', setonduty_path(:id=>onld.id) if onld.id&&(is_admin?||is_company_admin?) %>
    </td>

    <%
      t=0.hours
      while t < 24.hours do 
        busytime=0
        order_ids=''
          @aorders.each do |o|
            if o.is_d_busy(onld.aauto.id, t.seconds)
                busytime+=1
                order_ids+="#{o.id},"
            end
          end
          order_ids.chop!    
          if busytime==0 %>
            <td class='hoverable time' data-orderid='[]'>&nbsp;</td>
          <%end%>
          <% if busytime==1 %>
            <td class='hoverable timebusy' data-orderid='[<%= order_ids %>]' >|</td>
          <%end%>
          <% if busytime>1 %>
            <td class='hoverable timeverybusy' data-orderid='[<%= order_ids %>]' >
              <%= busytime %>
            </td>
          <%end%>
      <%
      t+=10.minutes
      end%>
    <td><%= link_to 'Удалить', onld, :method => :delete if onld.id&&(is_admin?||is_company_admin?) %></td>
      

  </tr>
<% end %>

<% if is_admin?||is_company_admin? %>
  <tr class="ruler">
    <td colspan="151"></td>
  </tr>

  <tr>
    
        <td colspan="151">
          <%= form_for(@onlineauto) do |f| %>
          <%= f.hidden_field :odate_id %>
          <%= f.collection_select(:aauto_id, Aauto.all, :id, :name_autodesc, :prompt => 'Не назначен', :size=>'5')  %>
          <%= f.submit 'Добавить' %>
          <%end%>
        </td>
  </tr>
<%end%>


</table>

app/views/aorders/_onlinedrivers.erb
<% if @onlinedriver.errors.any? %>
  <td colspan="8">
    <div id="error_explanation">
      <h2><%= pluralize(@aonlinedrivers.errors.count, "ошибки! ") %> - ошибки  делают сохранение невозможным.:</h2>
      <ul>
      <% @aorder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </td>
  <br/>
  <%end%>
Справочник доступных водителей:

<%= button_to 'Заполнить из предыдущего дня', filldrivers_path if is_admin?%>
<table class="onlinedriverlist">
  <tr>
    <th class="name">ФИО</th>
    <th class="autodesc">Описание авто</th>
    <th class="autonumber">Номер авто</th>
    <th class="contact">Тел. водителя</th>
    <th class="onduty">Примечание</th>
    <th class="todel"> </th>
    <th class="toduty"> </th>

    <%
      t=9.hours
      while t <= 23.hours do %>
        <%  if  t.gcd(1.hour.to_i)==1.hour%>
          <% if t/3600>=18 or (t/3600>=13 and t/3600<14) %>
            <th colspan="6" class="notworkingtime"><%=t/3600%>-<%=t/3600+1%></th>
          <%else%>
            <th colspan="6" class="workingtime"><%=t/3600%>-<%=t/3600+1%></th>
          <%end%>
        <%end%>

      <%
        t+=10.minutes
        end
      %>

  </tr>


<% @onlinedrivers.each do |onld| %>
  <tr>
    <td><%= onld.adriver.name if onld.adriver %></td>
    <td><%= onld.adriver.autodesc if onld.adriver %></td>
    <td><%= onld.adriver.autonumber if onld.adriver %></td>
    <td><%= onld.adriver.contact if onld.adriver %></td>
    <td><%= 'Дежурный' if onld.onduty %></td>
    <td><%= link_to 'Удалить', onld, :method => :delete if is_admin? %></td>
    <td><%= link_to '(Не-)Дежурить', setonduty_path(:id=>onld.id) if is_admin? %></td>

    <%
    # ОСТОРОЖНО, ГОВНОКОД!!!! Но переделывать лень.
      t=9.hours
      while t < 24.hours do 
        busytime=0
        order_ids=''
          @aorders.each do |o|
            if o.is_d_busy(onld.adriver.id, t.seconds)
                busytime+=1
                order_ids+="#{o.id},"
            end
          end
          order_ids.chop!    
          if busytime==0 %>
            <td class='hoverable time' data-orderid='[]'>&nbsp;</td>
          <%end%>
          <% if busytime==1 %>
            <td class='hoverable timebusy' data-orderid='[<%= order_ids %>]' >|</td>
          <%end%>
          <% if busytime>1 %>
            <td class='hoverable timeverybusy' data-orderid='[<%= order_ids %>]' >
              <%= busytime %>
            </td>
          <%end%>
      <%
      t+=10.minutes
      end%>

  </tr>
<% end %>

<% if is_admin? %>
  <tr class="ruler">
    <td colspan="97"></td>
  </tr>

  <tr>
    
        <td colspan="97">
          <%= form_for(@onlinedriver) do |f| %>
          <%= f.hidden_field :odate_id %>
          <%= f.collection_select(:adriver_id, Adriver.all, :id, :name, :prompt => 'Не назначен', :size=>'5')  %>
          <%= f.submit 'Добавить' %>
          <%end%>
        </td>
  </tr>
<%end%>


</table>

app/views/aorders/edit.html.erb
<h1>Редактирование заказа</h1>

<tr>
  <%= render 'form' %>
</tr>

<%= link_to 'Подробно', @aorder %> |
<%= link_to 'Назад в список заказов', aorders_path %>

app/views/aorders/index.html.erb
 
<div id="top_all">

  <% unless is_not_tm2_user? %>
    <div id="top_msg">
      Заказы автомобиля на день:
        <%= @odate.thedate %>
        (<%= @odate.showstatus %>)
    </div>
  <% end %>

  <div id="top_btns">

<%  if is_admin?  %>
    <%=
      button_to( 'Закрыть день',
      set_day_status_path(:id=>@odate.id , day_action: 'day_close'),
      {:id=>:one_btn, :disabled=>@odate.isclosed})
    %>
    <%=
      button_to( 'Открыть день',
      set_day_status_path(:id=>@odate.id , day_action: 'day_open'),
      {:id=>:one_btn, :disabled=>!@odate.isclosed})
    %>
<%end%>
    
<%  if check_tabel_rights?  %>
    <%=
      link_to 'Табель сотрудников', tabel_path
    %>


<%end%>
  </div>

  <div id="status_wrapper">

      <% if session[:user]  %>
      Вы работаете как:
          <%= session[:user].name %> (ID=<%=session[:user].id %>)<br/>
      Со статусом:
          <%= session[:user].userlevel.name %> <br />

<% unless is_not_tm2_user? %>      
      Компания:
          <%= session[:user].company.name if session[:user].company %> <br/>
<%end%>


      <%= link_to 'Выйти из системы', log_out_path %><br/>
      <%= 
      # link_to 'Обновить список заказов', uporderstable_path, :remote=>true    решили что лишнее
      %>
      <%end%>
  </div>

</div>

<%=  image_tag('pic2.gif', :size=>"180x80",  :id=>:pic1) %>

<% unless is_not_tm2_user? %>

  <div id="date_change">
    <div id="date_msg">Изменение даты</div>
    <div id="date_field">

      <%= form_tag(setdate_path) do%>
         <%= text_field_tag :tek_date, @odate.thedate, :size=>8 %>
         <%= submit_tag 'установить (обновить инф.)' %>
      <% end %>

    </div>
  </div>

  <%= content_tag(:div, raw(@error_text), id: "flash", class:"field_with_errors") if @error_text %>

  <div id="olist_wrapper">
    <div id="olist_div">
        <%= render 'olist' %>
    </div>

    <div id="new_order">
        Добавление нового заказа:
        <%= render 'form' unless @odate.isclosed%>
    </div>

    <div id="onlineautos">
      <%= render 'onlineautos' %>
    </div>



<% end %>  <!-- unless is_not_tm2_user? -->

    <div id="links">
        <br />  <%= link_to 'Справочник всех автомобилей', aautos_path unless is_not_tm2_user? %>
        <br/>
        <br />  <%= link_to 'Список пользователей', users_path %>
        <br/>
        <br /> <%= link_to 'Список компаний', companies_path if is_admin? %>
        <br/>
        <br /> <%= link_to 'Список отделов', departments_path if is_admin? %>
        <br/>
        <br /> <%= link_to 'Статистика по автомобилям', stat_path unless is_not_tm2_user?%>
        <br/>
        <br /> <!-- %= link_to 'Статистика по телефонам ЦИК ', calls_path % -->

    </div>

  </div>

app/views/aorders/new.html.erb
<h1>New aorder</h1>

<table>
  <tr>
    <%= render 'form' %>
  </tr>
</table>


<%= link_to 'Back', aorders_path %>

app/views/aorders/show.html.erb
<p id="notice"><%= notice %></p>
<h2> Заявка на использование автомобиля</h2>

<p>
  <b>На дату:</b>
  <%= @aorder.odate.thedate %>
</p>

<p>
  <b>Кто едет:</b>
  <%= @aorder.onname %>
</p>
<p>
<b>Отдел:</b>
  <%= @aorder.ondepartment %>
</p>

<b>Контактный телефон:</b>
  <%= @aorder.contact %>
</p>

<p>
  <b>Куда:</b>
  <%= @aorder.adestination %>
</p>

<p>
  <b>с:</b>
  <%= @aorder.ftime.strftime("%H:%M") %>
</p>

<p>
  <b>по:</b>
  <%= @aorder.totime.strftime("%H:%M") %>
</p>

<p>
  <b>Назначен автомобиль:</b>
  <%= @aorder.aauto.name if @aorder.aauto %>
</p>

<p>
  <b>Кто подал заявку (хозяин заявки):</b>
  <%= @aorder.user.name %>
  (ID=<%=  @aorder.user_id %>)
</p>


<%= link_to 'Редактировать', edit_aorder_path(@aorder) if (is_admin? and !@aorder.odate.isclosed) %> |
<%= link_to 'Назад в список заказов', aorders_path %>