config/routes.rb
Tm2::Application.routes.draw do

  # resources :callists
  # resources :calls


  resources :departments

  resources :companies

  resources :actions

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "setdate" => "aorders#setdate", :as => "setdate"
  post "fillautos" => "onlineautos#fillautos", :as => "fillautos"
  match "setonduty" => "onlineautos#setonduty", :as => "setonduty", via: [:get, :post]
  match "setosort" => "aorders#setosort", :as => "setosort", via: [:get, :post]
  match "aorders/:id/cancel" =>"aorders#ocancel", :as => "aorder_cancel", via: [:get, :post]
  match "uporderstable" => "aorders#uporderstable", :as =>"uporderstable", via: [:get, :post]
  match "tabel" => "actions#tabel", :as =>"tabel", via: [:get, :post]
  # post "password_reset" => "users#password_reset", :as => "password_reset"
  match "aorders/:id/edit_odometer" =>"aorders#edit_odometer", :as => "edit_aorder_odometer", via: [:get, :post]

  match "stat" => "stat#index", :as =>"stat", via: [:get, :post]
  match "stat_xml" => "stat#index_xml", :as =>"stat_xml", via: [:get, :post]
  match "routelist" => "stat#routelist", :as =>"routelist", via: [:get, :post]


#  get "onlineautos/:action/:id" => "onlineautos#index", :as=>"onlineautos"

  resources :users
  resources :sessions
  resources :onlineautos

  resources :aautos
  resources :aorders

  match '/set_day_status' => 'aorders#set_day_status', :as=>'set_day_status', via: [:get, :post]


  root :to => "sessions#new"
 
end

app/models/aauto.rb
class Aauto < ActiveRecord::Base
  has_many :aorders;
 
  has_many :onlideautos;
  has_many :odate, :through=>:onlineautos;

  def name_autodesc
  	self.name+' ('+self.autodesc+')'
  end

  def self.used_in_orders(aorders)

# Заменил плюком :)))    можно удалить если плюк не будет глючить
#		auto_ids=[]
#		aorders.each {|aorder| auto_ids<<aorder.aauto.id }
#		Aauto.where(id: auto_ids)

   Aauto.where(id: aorders.pluck(:aauto_id))

  end
 
end

app/controllers/aautos_controller.rb
# encoding: utf-8

class AautosController < ApplicationController
  before_action :require_login  
  before_action :is_admin, :except => [:index, :show]
 

  # GET /aautos
  # GET /aautos.xml
  def index
    @aautos = Aauto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aautos }
    end
  end

  # GET /aautos/1
  # GET /aautos/1.xml
  def show
    @aauto = Aauto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @aauto }
    end
  end

  # GET /aautos/new
  # GET /aautos/new.xml
  def new
    @aauto = Aauto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aauto }
    end
  end

  # GET /aautos/1/edit
  def edit
    @aauto = Aauto.find(params[:id])
  end

  # POST /aautos
  # POST /aautos.xml
  def create
    @aauto = Aauto.new(params[:aauto])

    respond_to do |format|
      if @aauto.save
        format.html { redirect_to(@aauto, :notice => 'Aauto was successfully created.') }
        format.xml  { render :xml => @aauto, :status => :created, :location => @aauto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aauto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aautos/1
  # PUT /aautos/1.xml
  def update
    @aauto = Aauto.find(params[:id])

    respond_to do |format|
      if @aauto.update_attributes(params[:aauto])
        format.html { redirect_to(@aauto, :notice => 'Aauto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aauto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aautos/1
  # DELETE /aautos/1.xml
  def destroy
    @aauto = Aauto.find(params[:id])
    @aauto.destroy

    respond_to do |format|
      format.html { redirect_to(aautos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/aautos_helper.rb
module AautosHelper
end

app/views/aautos/_form.html.erb
<%= form_for(@aauto) do |f| %>
  <% if @aauto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aauto.errors.count, "error") %> - ошибки  делают сохранение невозможным:</h2>

      <ul>
      <% @aauto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Автомобиль" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :autodesc, "Водитель" %><br />
    <%= f.text_field :autodesc %>
  </div>
  <div class="field">
    <%= f.label :autonumber, "Госномер авто" %><br />
    <%= f.text_field :autonumber %>
  </div>
  <div class="field">
    <%= f.label :contact, "Контактный тел. водителя" %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit 'Создать'%>
  </div>
<% end %>

app/views/aautos/edit.html.erb
<h1>Editing aauto</h1>

<%= render 'form' %>

<%= link_to 'Show', @aauto %> |
<%= link_to 'Back', aautos_path %>

app/views/aautos/index.html.erb
<h1>Список автомобилей</h1>

<table class="allorderlist">
  <tr>
    <th>ID</th>
    <th>Автомобиль</th>
    <th>Водитель</th>
    <th>Госномер авто</th>
    <th>Контакт</th>
    <th colspan="3">Управление</th>
  </tr>

<% @aautos.each do |aauto| %>
  <tr>
    <td><%= aauto.id %></td>
    <td><%= aauto.name %></td>
    <td><%= aauto.autodesc %></td>
    <td><%= aauto.autonumber %></td>
    <td><%= aauto.contact %></td>
    <td><%= link_to 'Показать', aauto %></td>
    <td><%= link_to 'Изменить', edit_aauto_path(aauto) if is_admin? %></td>
    <td><%= link_to 'Удалить', aauto, :confirm => 'Вы уверены? Трижды подумайте! Удалится из всех заказов! Безвозвратно! И автор хотел это переделать, скажите ему если он забыл.', :method => :delete if is_admin? %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый автомобиль', new_aauto_path if is_admin?%>
<br />
<%= link_to 'Вернуться в список заказов (на главную)', aorders_path   %>

app/views/aautos/new.html.erb
<h1>Новый Автомобиль</h1>

<%= render 'form' %>

<%= link_to 'Назад в список авто', aautos_path %> <br/>
<%= link_to 'Назад в заказы', aorders_path %>

app/views/aautos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Автомобиль:</b>
  <%= @aauto.name %>
</p>

<p>
  <b>Водитель:</b>
  <%= @aauto.autodesc %>
</p>

<p>
  <b>Госномер:</b>
  <%= @aauto.autonumber %>
</p>

<p>
  <b>Контактный тел. водителя:</b>
  <%= @aauto.contact %>
</p>


<%= link_to 'Изменить', edit_aauto_path(@aauto) if is_admin?%> |
<%= link_to 'Список автомобилей', aautos_path %>
<br />
<%= link_to 'Список заказов', aorders_path %>