config/routes.rb
Tm2::Application.routes.draw do

  # resources :callists
  # resources :calls


  resources :departments

  resources :companies

  resources :actions

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "setdate" => "aorders#setdate", :as => "setdate"
  post "fillautos" => "onlineautos#fillautos", :as => "fillautos"
  match "setonduty" => "onlineautos#setonduty", :as => "setonduty", via: [:get, :post]
  match "setosort" => "aorders#setosort", :as => "setosort", via: [:get, :post]
  match "aorders/:id/cancel" =>"aorders#ocancel", :as => "aorder_cancel", via: [:get, :post]
  match "uporderstable" => "aorders#uporderstable", :as =>"uporderstable", via: [:get, :post]
  match "tabel" => "actions#tabel", :as =>"tabel", via: [:get, :post]
  # post "password_reset" => "users#password_reset", :as => "password_reset"
  match "aorders/:id/edit_odometer" =>"aorders#edit_odometer", :as => "edit_aorder_odometer", via: [:get, :post]

  match "stat" => "stat#index", :as =>"stat", via: [:get, :post]
  match "stat_xml" => "stat#index_xml", :as =>"stat_xml", via: [:get, :post]
  match "routelist" => "stat#routelist", :as =>"routelist", via: [:get, :post]


#  get "onlineautos/:action/:id" => "onlineautos#index", :as=>"onlineautos"

  resources :users
  resources :sessions
  resources :onlineautos

  resources :aautos
  resources :aorders

  match '/set_day_status' => 'aorders#set_day_status', :as=>'set_day_status', via: [:get, :post]


  root :to => "sessions#new"
 
end

app/controllers/stat_controller.rb
class StatController < ApplicationController
	include ApplicationHelper
  before_action :require_login  

	def index
		@date_begin = params[:first_date] ? params[:first_date] : Time.now.to_date-1.day
		@date_end = params[:last_date] ? params[:last_date] : Time.now.to_date
		@aorders=Aorder.get_by_dates(@date_begin, @date_end, params[:sorton]).order(:ftime)
		@auto_list=Aauto.used_in_orders(@aorders)

	end

	def index_xml
		@aorders=Aorder.get_by_dates(params[:first_date], params[:last_date])

		send_data @aorders.to_xml(
			:procs =>   [lambda{ |options, record| options[:builder].tag!('department', record.department.name) },
							lambda{ |options, record| options[:builder].tag!('driver', record.aauto.name_autodesc) if record.aauto },
							lambda{ |options, record| options[:builder].tag!('date', record.odate.thedate) },
							lambda{ |options, record| options[:builder].tag!('distance', record.distance) },
							lambda{ |options, record| options[:builder].tag!('user_author', record.user.name) },
							lambda{ |options, record| options[:builder].tag!('ftime_xml', record.ftime.strftime("%H:%M") ) },
							lambda{ |options, record| options[:builder].tag!('totime_xml', record.totime.strftime("%H:%M") ) },
							lambda{ |options, record| options[:builder].tag!('totaltime_seconds', record.duration_seconds ) }
						],
			:except =>  [:aauto_id, :department_id, :odate_id, :user_id, :ftime, :totime, :iscanceled, :ondepartment, :updated_at],
			:skip_types => true
			), 
		:type => 'text/xml; charset=UTF-8;',
		:disposition => "attachment",
		:filename => "stat_#{params[:first_date]}-#{params[:last_date]}.xml"
	end


	def routelist
#	@aorders = Aorder.get_by_dates(params[:first_date], params[:last_date]).where("aorders.aauto_id= ? ", params[:auto_id])
#	@odates = Odate.used_in_orders(@aorders).order(:thedate)

# получаем массив  интересующих нас aorders по датам и машине
		aorders = Aorder.get_by_dates( params[:first_date], params[:last_date] ).where("aorders.aauto_id IN (?) ", params[:auto_id]).reorder(:thedate)

# получаем idшки дней где оно біло
		used_odate_ids = aorders.pluck(:odate_id).uniq

#формируем хеш {дата  => [масив ордеров] }
		@days_of_orders={}

		used_odate_ids.each do |curr_odate_id|
			@days_of_orders[ Odate.find_by_id(curr_odate_id) ] = aorders.where("odate_id = ?", curr_odate_id).order(:ftime)
		end


		# @auto = Aauto.find_all_by(id: params[:auto_id])
		@auto = Aauto.find(params[:auto_id])

		respond_to do |format|
		  format.html # routelist.html.erb
		  format.xml  { }
		end
	end

end

app/helpers/stat_helper.rb
module StatHelper
end

app/views/stat/_body.erb
<% @aorders.each do |aorder| %>
  <tr>
    <td><%= aorder.id %></td>
    <td><%= aorder.onname %></td>
    <td><%= aorder.department.name if aorder.department %></td>
    <td><%= aorder.contact %></td>
    <td><%= aorder.adestination %></td>
    <td><%= aorder.ftime.strftime("%H:%M") %></td>
    <td><%= aorder.totime.strftime("%H:%M") %></td>
    <td><%= hm(aorder.duration_seconds) %></td>
    <td><%= aorder.aauto.name_autodesc if aorder.aauto %></td>
    <td><%= aorder.comment %></td>

    <%= td_odometer(aorder.odobegin, aorder.odoend, aorder.outofcity) do %>
        <%= aorder.odobegin %>
    <%end%>
    
    <%= td_odometer(aorder.odobegin, aorder.odoend, aorder.outofcity) do %>
        <%= aorder.odoend %>
    <%end%>

    <td><%= aorder.distance %></td>



    <td <%= 'class= baddate' if !aorder.odate.isclosed %> ><%= link_to( aorder.odate.thedate, setdate_path( tek_date: aorder.odate.thedate), method: :post ) %></td>
    <td><%= aorder.user.name %></td>


  </tr>
<% end %>

app/views/stat/_head.erb
<tr>
    <th class="nomer"> <%= link_to('№', stat_path(:sorton=>'aorders.id', :first_date=>@date_begin, :last_date=>@date_end))%> </th>
    <th class="fio"> <%= link_to('Кто едет', stat_path(:sorton=>'aorders.onname', :first_date=>@date_begin, :last_date=>@date_end))%> </th>
    <th class="depart"><%= link_to('Отдел  (сортировка по id)', stat_path(:sorton=>'aorders.department_id', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="contact"><%= link_to('Тел.', stat_path(:sorton=>'aorders.contact', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="destination"><%= link_to('Куда', stat_path(:sorton=>'aorders.adestination', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="time"><%= link_to('"с"', stat_path(:sorton=>'aorders.ftime', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="time"><%= link_to('"по"', stat_path(:sorton=>'aorders.totime', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="duration"><%= link_to('Длительность', stat_path(:sorton=>'aorders.totime - aorders.ftime', :first_date=>@date_begin, :last_date=>@date_end)) %></th>

    <th class="auto"><%= link_to('Автомобиль  (сортировка по id)', stat_path(:sorton=>'aorders.aauto_id', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="comment"><%= link_to('Коммент.', stat_path(:sorton=>'aorders.comment', :first_date=>@date_begin, :last_date=>@date_end))%></th>
    <th class="odometer"><%= link_to('Нач. км.', stat_path(:sorton=>'aorders.odobegin', :first_date=>@date_begin, :last_date=>@date_end)) %></th>
    <th class="odometer"><%= link_to('Кон. км.', stat_path(:sorton=>'aorders.odoend', :first_date=>@date_begin, :last_date=>@date_end)) %></th>

    <th class="odometer"><%= link_to('Дистанция', stat_path(:sorton=>'aorders.odoend - aorders.odobegin', :first_date=>@date_begin, :last_date=>@date_end)) %></th>


    <th class="management"><%= link_to('Дата заказа', stat_path(:sorton=>'odates.thedate', :first_date=>@date_begin, :last_date=>@date_end)) %></th>
    <th class="owner"><%= link_to('Заявитель (сортировка по id)', stat_path(:sorton=>'aorders.user_id', :first_date=>@date_begin, :last_date=>@date_end)) %></th>


</tr>

app/views/stat/index.html.erb
<h1>Статистика</h1>
<i> Примечание - длительность поезки учитывается в статистике только если  автомобиль двигался (пробег по заявке более нуля) </i>
<h2> Заказы автомобилей за период с <%= @date_begin %> по <%= @date_end %> </h2>

    <%= form_tag(stat_path) do %>

       <%= text_field_tag :first_date, @date_begin, :size=>8 %>
       <%= text_field_tag :last_date, @date_end, :size=>8 %>
       <%= submit_tag 'поменять (обновить инф.)' %>

    <% end %>

	<table class="allorderlist" "id=table_active" >
    <%= render 'head' %>
    <%= render 'body' %>
  </table>

  <%= form_tag(stat_xml_path, :format=> :xml) do %>

       <%= hidden_field_tag :first_date, @date_begin %>
       <%= hidden_field_tag :last_date, @date_end %>
       <%= submit_tag 'загрузить в xml (сортировки нет)' %>
  <% end %>


<h2> Сформировать маршрутные листы за указанный период </h2>
    <%= form_tag(routelist_path, :target =>'_blank', id: "auto_select_form") do %>
      <%= hidden_field_tag :first_date, @date_begin %>
      <%= hidden_field_tag :last_date, @date_end %>

       <%= label_tag :auto_id, 'по автомобилям (Ctrl+клик - выбор нескольких)' %>
       <%= select_tag :auto_id,  options_for_select( @auto_list.collect{|u| [u.name_autodesc, u.id]}), {multiple: true, size: "#{@auto_list.size}"}  %>

      <%= submit_tag 'сформировать' %>
    <% end %>

    <%= link_to 'Вернуться в список заказов (на главную)', aorders_path   %>

app/views/stat/routelist.html.erb
<% 
	total_alldays = 0
	total_alldays_time = 0
	total_alldays_outofcity = 0
%>

<% @days_of_orders.each do|odate, orders|  
			total_all = 0
			total_outofcity = 0
			total_time = 0
%>
			<h2>Маршрутний лист по автівкам: 
				<% @auto.each do |a|  %>
					<%= a.name_autodesc+", " %>
				<% end %>
			</h2> 


			<h3>Дата: <%= odate.thedate.strftime('%d.%m.%Y') %> 
				<% if !odate.isclosed%>
					<div class='field_with_errors'> - День не закрито !</div>
				<% end %>

			</h3>
			<table class="routelist">
				<tr>
					<th id='adestination'>Пункт(и) призначеня</th>
					<th id='ftime'>Час початку руху</th>
					<th id='totime'>Час закінченя руху</th>
					<th id='total_time'>Тривалість</th>
					<th id='odobegin'>Спідометр на початку</th>
					<th id='odoend'>Спідометр в кінці</th>
					<th id='distance'>Дистанція всього, км.</th>
					<th id='outofcity'>Із них ресурсні (поза містом), км.</th>
					<th id='onname'>ПІБ відповідальної особи</th>
				</tr>

				<% orders.each do |order|
					total_all += order.distance
					total_alldays += order.distance
					total_time += order.duration_seconds
					total_alldays_time += order.duration_seconds

					total_outofcity += order.outofcity
					total_alldays_outofcity += order.outofcity
				%>
					<tr>
						<td><%= order.adestination %></td>
						<td><%= order.ftime.strftime("%H:%M") %></td>
						<td><%= order.totime.strftime("%H:%M") %></td>
						<td><%= hm(order.duration_seconds) %></td>
						<td><%= order.odobegin %></td>
						<td><%= order.odoend %></td>
						<td><%= order.distance %></td>
						<td><%= order.outofcity %></td>
						<td><%= order.onname %></td>		
					</tr>
				<% end %>
		  </table>

		  <h4>Загальна тривалість: <%= hm(total_time) %></h4>
		  <h4>Всього за день, км: <%= total_all %></h4>
		  <h4>Із них бюджетні (по місту), км: <%= total_all-total_outofcity %></h4>
		  <h4>Із них ресурсні (поза містом), км:<%= total_outofcity %></h4>
		  <p class = 'break_page'> ---наступна сторінка-- </p>

<% end %>

  <h4>Загальна тривалість за всі дні : <%= "#{hm(total_alldays_time)} (годин:хвилин)"  %> </h4>
  <h4>Всього пробіг за всі дні, км: <%= total_alldays %></h4>
  <h4>Із них бюджетні (по місту), км: <%= total_alldays - total_alldays_outofcity %></h4>
  <h4>Із них ресурсні (поза містом), км:<%= total_alldays_outofcity %></h4>