config/routes.rb
Tm2::Application.routes.draw do

  # resources :callists
  # resources :calls


  resources :departments

  resources :companies

  resources :actions

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "setdate" => "aorders#setdate", :as => "setdate"
  post "fillautos" => "onlineautos#fillautos", :as => "fillautos"
  match "setonduty" => "onlineautos#setonduty", :as => "setonduty", via: [:get, :post]
  match "setosort" => "aorders#setosort", :as => "setosort", via: [:get, :post]
  match "aorders/:id/cancel" =>"aorders#ocancel", :as => "aorder_cancel", via: [:get, :post]
  match "uporderstable" => "aorders#uporderstable", :as =>"uporderstable", via: [:get, :post]
  match "tabel" => "actions#tabel", :as =>"tabel", via: [:get, :post]
  # post "password_reset" => "users#password_reset", :as => "password_reset"
  match "aorders/:id/edit_odometer" =>"aorders#edit_odometer", :as => "edit_aorder_odometer", via: [:get, :post]

  match "stat" => "stat#index", :as =>"stat", via: [:get, :post]
  match "stat_xml" => "stat#index_xml", :as =>"stat_xml", via: [:get, :post]
  match "routelist" => "stat#routelist", :as =>"routelist", via: [:get, :post]


#  get "onlineautos/:action/:id" => "onlineautos#index", :as=>"onlineautos"

  resources :users
  resources :sessions
  resources :onlineautos

  resources :aautos
  resources :aorders

  match '/set_day_status' => 'aorders#set_day_status', :as=>'set_day_status', via: [:get, :post]


  root :to => "sessions#new"
 
end

app/controllers/actions_controller.rb
# encoding: utf-8

require 'date'
class ActionsController < ApplicationController
  before_action :require_login
  before_action :check_tabel_rights



  # GET /actions
  # GET /actions.xml
  
  def index
    @actions = Action.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @actions }
    end
  end

  def tabel

    params[:company_id] && @company=Company.find_by_id(params[:company_id])
    @company||=session[:user].company

    if is_admin?
      @company ? @users=@company.users.all : @users=User.all
      @companies=Company.all
    elsif is_alltabeluser?
      @company ? @users=@company.users.all : @users=User.all
      @companies=Company.all
    else
      @users=@company.users.all
      @companies=[session[:user].company]
    end
    
    @odate=session[:working_date]
    @odate.thedate=params[:tek_date] if params[:tek_date]
    @year=session[:working_date].thedate.year
    @month=session[:working_date].thedate.month
    @day=session[:working_date].thedate.day

    @days_in_month=days_in_month(@month, @year)


  end

  # GET /actions/1
  # GET /actions/1.xml
=begin
  def show
    @action = Action.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @action }
    end
  end
=end

  # GET /actions/new
  # GET /actions/new.xml
  def new
    @action = Action.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @action }
    end
  end
=begin
  # GET /actions/1/edit
  def edit
    @action = Action.find(params[:id])
  end
=end

  # POST /actions
  # POST /actions.xml
  def create
    @action = Action.new(params[:action])

    respond_to do |format|
      if @action.save
        format.html { redirect_to(@action, :notice => 'Action was successfully created.') }
        format.xml  { render :xml => @action, :status => :created, :location => @action }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @action.errors, :status => :unprocessable_entity }
      end
    end
  end

=begin
  # PUT /actions/1
  # PUT /actions/1.xml
  def update
    @action = Action.find(params[:id])

    respond_to do |format|
      if @action.update_attributes(params[:action])
        format.html { redirect_to(@action, :notice => 'Action was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @action.errors, :status => :unprocessable_entity }
      end
    end
  end
=end

=begin
  # DELETE /actions/1
  # DELETE /actions/1.xml
  def destroy
    @action = Action.find(params[:id])
    @action.destroy

    respond_to do |format|
      format.html { redirect_to(actions_url) }
      format.xml  { head :ok }
    end
  end
=end

  private
  def days_in_month(month, year)
    (Date.new(year,12,31).to_date<<(12-month)).day
  end



end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/_form.html.erb
<%= form_for(@action) do |f| %>
  <% if @action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action.errors.count, "error") %> prohibited this action from being saved:</h2>

      <ul>
      <% @action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actions/edit.html.erb
<h1>Editing action</h1>

<%= render 'form' %>

<%= link_to 'Show', @action %> |
<%= link_to 'Back', actions_path %>

app/views/actions/index.html.erb
<h1>Listing actions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Type</th>
    <th>Первое событие</th>
    <th>Последняя проверка</th>
  </tr>

<% @actions.each do |action| %>
  <tr>
    <td><%= action.user.name %></td>
    <td><%= action.kind %></td>
    <td><%= action.created_at %></td>
    <td><%= action.updated_at %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Action', new_action_path %>

app/views/actions/new.html.erb
<h1>New action</h1>

<%= render 'form' %>

<%= link_to 'Back', actions_path %>

app/views/actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @action.kind %>
</p>

<p>
  <b>User:</b>
  <%= @action.user %>
</p>


<%= link_to 'Edit', edit_action_path(@action) %> |
<%= link_to 'Back', actions_path %>

app/views/actions/tabel.erb
<h1>Компания: <%= @company.name %>, месяц: <%= ::MONTHNAMES_RUS[@month] %></h1>
  <div id="tabel_company">
    <%= form_tag(tabel_path) do%>
       <%= label_tag 'Изменить компанию на:' %>
       <%= collection_select(nil, :company_id, @companies, :id, :name, {:selected => @company.id})%>

       <%= label_tag 'Изменить дату на:' %>
       <%= text_field_tag :tek_date, @odate.thedate, :size=>8 %>
       <%= submit_tag 'ОК' %>
    <% end %>
  </div>

<table class="allorderlist" id="tabel">
  <tr>
    <th class="id"> ID </th>
    <th class="name"> Имя </th>
    <%  @days_in_month.times do |day| %>
      <th> <%= day+1 %> </th>
    <% end %>



  </tr>
<% @users.each do |user|
     @first_login=Array.new
     @last_login=Array.new
 %>
  <tr>
    <td class="id""><%= user.id %></td>
    <td class="name"><%= user.name+", вход:" %></td>
    <%  @days_in_month.times do |day| %>
      <td>
            <%=
              @first_login[day]=get_first_login(user.id,day+1,@month,@year)
              @first_login[day] ? @first_login[day].strftime("%H: %M") : "-"
            %>
      </td>
    <% end %>
</tr>


  <tr>
    <td></td>
    <td>Выход:</td>
    <%  @days_in_month.times do |day| %>
      <td> <%=
              @last_login[day] = get_last_login(user.id,day+1,@month,@year)
              @last_login[day] ? @last_login[day].strftime("%H: %M") : "-"
           %>
      </td>
    <% end %>
  </tr>

  <tr>
    <td class="bottom"></td>
    <td class="bottom">Отработано:</td>
    <%  @days_in_month.times do |day|
          if @last_login[day] and @first_login[day]
            worked_time = Time.at(@last_login[day] - @first_login[day])
            worked_hours = worked_time.to_f/60/60
            worked_time_s = worked_time.utc.strftime("%H: %M")
          else
            worked_hours = 0
            worked_time_s = "-"
          end
      %>
      <td <%= worked_hours>9 ? 'class=bottom' : 'class=bad_day' %> >
          <%= worked_time_s %>
      </td>

    <% end %>
  </tr>


<%end%>

</table>

<%=  link_to 'Назад в список заказов', aorders_path %>